version: "3"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - USER=<secret>
      - "PASS=<secret>"
      - CONNECT=p2p
      - TECHNOLOGY=NordLynx
      - NETWORK=0.0.0.0/0
  torrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - qbittorrent-config:/config
      - /jellyfin-files:/files
    depends_on:
      - vpn
    restart: unless-stopped
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=https://junkfoodmountain.nl
    volumes:
      - jellyfin-config:/config
      - /jellyfin-files:/files
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    links:
      - vpn:service
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=<secret>
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
    volumes:
      - swag-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    depends_on:
      - jellyfin
volumes:
  jellyfin-config:
  qbittorrent-config:
  swag-config:
