version: "3.9"
services:
  vpn:
    image: ghcr.io/bubuntux/nordvpn
    cap_add:
      - NET_ADMIN
    environment:
      - USER=<secret>
      - "PASS=<secret>"
      - CONNECT=p2p
      - TECHNOLOGY=NordLynx
      - NETWORK=0.0.0.0/0
  torrent:
    container_name: qbittorrent
    image: ghcr.io/linuxserver/qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - qbittorrent-config:/config
      - /jellyfin-files:/files
    depends_on:
      - vpn
    restart: unless-stopped
  jellyfin:
    image: ghcr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - JELLYFIN_PublishedServerUrl=<secret>
    volumes:
      - jellyfin-config:/config
      - /jellyfin-files:/files
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    links:
      - vpn:service
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=<secret>
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare #optional
    volumes:
      - swag-config:/config
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    depends_on:
      - jellyfin
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - sonarr-config:/config
      - /jellyfin-files/:/files #optional
    ports:
      - 8989:8989
    restart: unless-stopped
  jackett:
    image: ghcr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
      - AUTO_UPDATE=true #optional
    volumes:
      - jackett-config:/config
      - /jellyfin-files/:/files
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Amsterdam
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Amsterdam
    volumes:
      - radarr-config:/config
      - /jellyfin-files/:/files
    ports:
      - 7878:7878
    restart: unless-stopped
volumes:
  jellyfin-config:
  qbittorrent-config:
  swag-config:
  jackett-config:
  sonarr-config:
  radarr-config:
